management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9001
spring:
  application:
    name: nacos-provider
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:7868
      config:
        server-addr: 127.0.0.1:7848
        namespace: summy-dev