management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9001
spring:
  application:
    name: nacos-provider
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.188:8868
      config:
        server-addr: 192.168.0.188:8848
        namespace: summy-dev